# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: jenkins-claim
# spec:
#   accessModes:
#     - ReadWriteMany
#   storageClassName: efs-sc
#   resources:
#     requests:
#       storage: 5Gi

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-claim2
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi